### ISSUE TITLE
pip3 install onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl error on raspberry pi 4

### ISSUE THREAD

**Issue by borgiaE** [nknytk/built-onnxruntime-for-raspberrypi-linux#2]
pip3 install onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement
    hashes=hashes,
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 264, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/pi/.local/lib/python3.7/site-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by nknytk** [comment]
If you are installing onnxruntime to system python3, I think venv is better.

Firstly install venv if you have not.
```
$ sudo apt install python3-venv
```

Then create venv and install onnxruntime.

```
$ python3 -m venv .venv
$ . .venv/bin/activate
$ pip install --upgrade pip wheel
$ pip install onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl
```

Installing onnxruntime to system python3 might need `sudo`.

```
$ sudo pip3 install onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl
```

**Comment by borgiaE** [comment]
It is working, the problem occurred when using wget to get onnxruntime-1.2.0-cp37-cp37m-linux_armv7l.whl, I downloaded it manually and it worked.
